import {
  Activity,
  ArrowLeftRight,
  BarChart3,
  Bell,
  BookOpen,
  Briefcase,
  Coins,
  CreditCard,
  Droplets,
  FileSearch,
  GitPullRequest,
  HandCoins,
  LayoutDashboard,
  LineChart,
  Power,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  SlidersHorizontal,
  TrendingUp,
  UserCheck,
  Users,
  Wallet,
} from "lucide-react";

const ADMIN_QUICK_ACTION_GROUPS = [
  {
    key: "surveillance",
    title: "Surveillance",
    description: "Risque, monitoring et supervision globale.",
    icon: ShieldAlert,
    className: "border-rose-200 bg-rose-50 hover:bg-rose-100/60",
    actions: [
      { label: "Utilisateurs", to: "/dashboard/admin/users", icon: Users, description: "Base client" },
      { label: "Limites clients", to: "/dashboard/admin/users/limits", icon: SlidersHorizontal, description: "Adapter les plafonds" },
      { label: "Gestion agents", to: "/dashboard/admin/agents", icon: Briefcase, description: "Comptes agents" },
      { label: "Dashboard", to: "/dashboard/admin/overview", icon: LayoutDashboard, description: "Dashboard principal" },
      { label: "Dashboard Lite", to: "/dashboard/admin/overview-lite", icon: LayoutDashboard, description: "Vue simplifiee" },
      { label: "Cas AML", to: "/dashboard/admin/aml-cases", icon: ShieldAlert, description: "Alertes AML ouvertes" },
      { label: "Carte de risque", to: "/dashboard/admin/risk-heatmap", icon: Activity, description: "Heatmap des risques" },
      { label: "Gestion liquidite", to: "/dashboard/admin/liquidity", icon: Droplets, description: "Tresorerie et liquidite" },
      { label: "Centre securite", to: "/dashboard/admin/security", icon: Bell, description: "Notifications et step-up admin" },
      { label: "Recherche audit", to: "/dashboard/admin/audit-search", icon: FileSearch, description: "Recherche globale audit" },
      { label: "Arbitrage", to: "/dashboard/admin/arbitrage", icon: TrendingUp, description: "Suivi arbitrage" },
      { label: "Arret d'urgence", to: "/dashboard/admin/kill-switch", icon: Power, description: "Kill switch" },
      { label: "Logs webhooks", to: "/dashboard/admin/webhooks", icon: ShieldCheck, description: "Journal webhooks" },
      { label: "Audit Log", to: "/backoffice/audit", icon: FileSearch, description: "Audit complet" },
      { label: "Monitoring", to: "/backoffice/monitoring", icon: BarChart3, description: "Monitoring backoffice" },
      { label: "Ops Dashboard", to: "/dashboard/admin/ops-dashboard", icon: Activity, description: "Operations et monitoring" },
      { label: "Urgences OPS", to: "/dashboard/admin/ops-urgencies", icon: ShieldAlert, description: "File transversale urgente" },
      { label: "Monitoring risque", to: "/dashboard/admin/risk", icon: ShieldAlert, description: "Surveillance risque" },
    ],
  },
  {
    key: "assistants",
    title: "Assistants admin",
    description: "Tous les assistants de la console.",
    icon: BookOpen,
    className: "border-cyan-200 bg-cyan-50 hover:bg-cyan-100/60",
    actions: [
      { label: "Guide assistants", to: "/dashboard/admin/assistants-guide", icon: BookOpen, description: "Guide global" },
      { label: "Assistant transfert", to: "/dashboard/admin/agent-chat", icon: BookOpen, description: "Aide transfert" },
      { label: "Assistant cash", to: "/dashboard/admin/cash-agent", icon: BookOpen, description: "Depot et retrait" },
      { label: "Assistant credit", to: "/dashboard/admin/credit-agent", icon: BookOpen, description: "Capacite credit" },
      { label: "Assistant KYC", to: "/dashboard/admin/kyc-agent", icon: BookOpen, description: "Conformite KYC" },
      { label: "Support transfert", to: "/dashboard/admin/transfer-support-agent", icon: BookOpen, description: "Suivi transfert" },
      { label: "Assistant wallet", to: "/dashboard/admin/wallet-agent", icon: BookOpen, description: "Support wallet" },
      { label: "Support wallet", to: "/dashboard/admin/wallet-support-agent", icon: BookOpen, description: "Incidents wallet" },
      { label: "Assistant escrow", to: "/dashboard/admin/escrow-agent", icon: BookOpen, description: "Suivi escrow" },
      { label: "Assistant P2P", to: "/dashboard/admin/p2p-agent", icon: BookOpen, description: "Suivi P2P" },
      { label: "Feedback IA", to: "/dashboard/admin/ai-feedback", icon: Sparkles, description: "Audit et apprentissage" },
      { label: "Synonymes IA", to: "/dashboard/admin/ai-synonyms", icon: Sparkles, description: "Gestion des alias" },
      { label: "Codes litiges", to: "/dashboard/admin/dispute-codes", icon: Sparkles, description: "Reference des codes" },
    ],
  },
  {
    key: "p2p",
    title: "P2P",
    description: "Trades, disputes et risque P2P.",
    icon: ArrowLeftRight,
    className: "border-emerald-200 bg-emerald-50 hover:bg-emerald-100/60",
    actions: [
      { label: "Suivi P2P", to: "/dashboard/admin/p2p/trades", icon: ArrowLeftRight, description: "Trades et activite" },
      { label: "Disputes", to: "/dashboard/admin/p2p/disputes", icon: FileSearch, description: "Litiges P2P" },
      { label: "Risque / alertes", to: "/dashboard/admin/p2p/risk", icon: ShieldAlert, description: "Risque P2P" },
    ],
  },
  {
    key: "escrowLedger",
    title: "Escrow et Ledger",
    description: "Escrow, comptabilite et balances.",
    icon: Coins,
    className: "border-violet-200 bg-violet-50 hover:bg-violet-100/60",
    actions: [
      { label: "File escrow", to: "/dashboard/admin/escrow", icon: Coins, description: "Dossiers escrow" },
      { label: "Audit Escrow", to: "/dashboard/admin/escrow/audit", icon: ShieldCheck, description: "Audit des escrows" },
      { label: "Balances", to: "/dashboard/admin/ledger/balances", icon: Wallet, description: "Balances globales" },
      { label: "Comptes T", to: "/dashboard/admin/ledger/t-accounts", icon: BookOpen, description: "Comptes T" },
      { label: "Journaux non equilibres", to: "/dashboard/admin/ledger/unbalanced-journals", icon: LineChart, description: "Anomalies ledger" },
      { label: "Idempotence scopes", to: "/dashboard/admin/ledger/idempotency-scopes", icon: LineChart, description: "Scopes d'idempotence" },
      { label: "Simulateur on-chain", to: "/dashboard/admin/onchain-simulator", icon: Activity, description: "Simulation blockchain" },
      { label: "Balances clients", to: "/dashboard/admin/balance-events", icon: LineChart, description: "Variations de soldes" },
    ],
  },
  {
    key: "operations",
    title: "Operations",
    description: "Portefeuilles, transferts et OPS.",
    icon: Wallet,
    className: "border-blue-200 bg-blue-50 hover:bg-blue-100/60",
    actions: [
      { label: "Portefeuilles", to: "/dashboard/admin/wallets", icon: Wallet, description: "Wallets globaux" },
      { label: "Wallets clients", to: "/dashboard/admin/client-wallets", icon: Users, description: "Wallets utilisateurs" },
      { label: "Corrections wallet", to: "/dashboard/admin/wallet-corrections", icon: Wallet, description: "Correction admin des soldes" },
      { label: "Analyse wallets", to: "/dashboard/admin/wallet-analysis", icon: LineChart, description: "Analyse des soldes" },
      { label: "Mobile Money", to: "/dashboard/admin/mobilemoney", icon: Wallet, description: "Operations mobile money" },
      { label: "Transferts externes", to: "/dashboard/admin/transfers", icon: GitPullRequest, description: "Flux externes" },
      { label: "Validations transferts", to: "/dashboard/admin/transfer-approvals", icon: GitPullRequest, description: "Approvals" },
      { label: "Gains transferts", to: "/dashboard/admin/transfer-gains", icon: TrendingUp, description: "Marge transferts" },
      { label: "Cash in/out", to: "/dashboard/admin/cash-requests", icon: Coins, description: "Depots et retraits" },
      { label: "Depots admin", to: "/dashboard/admin/cash-deposits", icon: Coins, description: "Recherche depots admin" },
      { label: "Depots mobile money BIF", to: "/dashboard/admin/payment-intents", icon: HandCoins, description: "Intents mobile money" },
      { label: "Demandes de paiement", to: "/dashboard/admin/payment-requests", icon: HandCoins, description: "Paiements a traiter" },
      { label: "Liquidite BIF (OPS)", to: "/dashboard/admin/ops/liquidity-bif", icon: Droplets, description: "Pilotage BIF" },
      { label: "Erreurs API", to: "/dashboard/admin/ops/errors", icon: Activity, description: "Erreurs et incidents" },
    ],
  },
  {
    key: "microfinance",
    title: "Microfinance",
    description: "Credits, lignes et produits.",
    icon: CreditCard,
    className: "border-amber-200 bg-amber-50 hover:bg-amber-100/60",
    actions: [
      { label: "Credits", to: "/dashboard/admin/loans", icon: CreditCard, description: "Demandes de pret" },
      { label: "Historique credits", to: "/dashboard/admin/credit-history", icon: BookOpen, description: "Historique des credits" },
      { label: "Lignes de credit", to: "/dashboard/admin/credit-lines", icon: BookOpen, description: "Capacites client" },
      { label: "Remboursement credit", to: "/dashboard/admin/credit-lines/repay", icon: BookOpen, description: "Rembourser un client" },
      { label: "Microfinance", to: "/dashboard/admin/microfinance", icon: Shield, description: "Vue microfinance" },
      { label: "Produits pret", to: "/dashboard/admin/loan-products", icon: BookOpen, description: "Configuration produits" },
    ],
  },
  {
    key: "tontines",
    title: "Tontines",
    description: "Pilotage des groupes et impayes.",
    icon: BarChart3,
    className: "border-fuchsia-200 bg-fuchsia-50 hover:bg-fuchsia-100/60",
    actions: [
      { label: "Dashboard tontines", to: "/dashboard/admin/tontines-dashboard", icon: BarChart3, description: "Vue d'ensemble" },
      { label: "Impayes tontines", to: "/dashboard/admin/tontines-arrears", icon: BarChart3, description: "Impayes et retards" },
      { label: "Creer une tontine", to: "/dashboard/admin/tontines/create", icon: BarChart3, description: "Nouveau groupe" },
      { label: "Membres tontines", to: "/dashboard/admin/tontines/members", icon: BarChart3, description: "Gestion membres" },
    ],
  },
  {
    key: "config",
    title: "Configuration",
    description: "Parametres et controles backoffice.",
    icon: Settings,
    className: "border-sky-200 bg-sky-50 hover:bg-sky-100/60",
    actions: [
      { label: "Parametres", to: "/dashboard/admin/settings", icon: Settings, description: "Configuration generale" },
      { label: "Verif KYC", to: "/dashboard/admin/kyc/reviews", icon: UserCheck, description: "Revue KYC" },
      { label: "Statistiques", to: "/dashboard/admin/analytics", icon: BarChart3, description: "Analyses consolidees" },
    ],
  },
  {
    key: "modeAgent",
    title: "Mode Agent",
    description: "Acces au hub agent depuis l'admin.",
    icon: Briefcase,
    className: "border-teal-200 bg-teal-50 hover:bg-teal-100/60",
    actions: [{ label: "Hub agent", to: "/dashboard/agent/dashboard", icon: Briefcase, description: "Basculer en mode agent" }],
  },
];

export function getAdminQuickActionGroups() {
  return ADMIN_QUICK_ACTION_GROUPS;
}
