import {
  ArrowDown,
  ArrowUp,
  BookOpen,
  CreditCard,
  Gift,
  Globe,
  LayoutDashboard,
  LineChart,
  MessageSquare,
  RefreshCcw,
  Send,
  Shield,
  Smartphone,
  Store,
  User,
  Wallet,
} from "lucide-react";

export const CLIENT_QUICK_ACTION_GROUPS = [
  {
    key: "wallet",
    title: "Portefeuille",
    description: "Vue generale, solde et historique.",
    icon: Wallet,
    className: "border-slate-200 bg-slate-50 hover:bg-white",
    actions: [
      { label: "Vue generale", to: "/dashboard/client/overview", icon: LayoutDashboard, description: "Synthese client" },
      { label: "Portefeuille", to: "/dashboard/client/wallet", icon: Wallet, description: "Wallet principal" },
      { label: "Transactions", to: "/dashboard/client/transactions", icon: RefreshCcw, description: "Mouvements applicatifs" },
      { label: "Historique balance", to: "/dashboard/client/balance-history", icon: LineChart, description: "Evolution des soldes" },
    ],
  },
  {
    key: "payments",
    title: "Paiements & transferts",
    description: "Envoyer, retirer, deposer et payer.",
    icon: Send,
    className: "border-emerald-200 bg-emerald-50 hover:bg-emerald-100/60",
    actions: [
      { label: "Demandes paiement", to: "/dashboard/client/payments", icon: Send, description: "Demandes entrantes et sortantes" },
      { label: "Reclamations", to: "/dashboard/client/support", icon: MessageSquare, description: "Suivre un incident" },
      { label: "Transfert interne", to: "/dashboard/client/transfer", icon: RefreshCcw, description: "Vers un autre utilisateur" },
      { label: "Transfert programme", to: "/dashboard/client/scheduled-transfers", icon: RefreshCcw, description: "Executions recurrentes" },
      {
        label: "Transfert externe programme",
        to: "/dashboard/client/scheduled-transfers/external",
        icon: Globe,
        description: "Vers un partenaire (recurrent)",
      },
      { label: "Epargne", to: "/dashboard/client/savings", icon: Wallet, description: "Objectifs et coffre" },
      { label: "Cartes virtuelles", to: "/dashboard/client/cards", icon: CreditCard, description: "Paiements web et plafonds" },
      { label: "Business", to: "/dashboard/client/business", icon: Store, description: "Equipe et roles" },
      { label: "API marchande", to: "/dashboard/client/merchant-api", icon: Globe, description: "Cles et webhooks" },
      { label: "Cagnottes", to: "/dashboard/client/pots", icon: Gift, description: "Collectes et objectifs" },
      { label: "Transfert externe", to: "/dashboard/client/external-transfer", icon: Globe, description: "Vers un partenaire" },
      { label: "Mobile Money", to: "/dashboard/client/mobiletopup", icon: Smartphone, description: "Recharge et services" },
      { label: "Depot cash", to: "/dashboard/client/deposit", icon: ArrowDown, description: "Demande de depot" },
      { label: "Retrait cash", to: "/dashboard/client/withdraw/bif", icon: ArrowUp, description: "Retrait BIF" },
      { label: "Retrait USDC", to: "/dashboard/client/withdraw/usdc", icon: ArrowUp, description: "Retrait crypto USDC" },
      { label: "Bonus", to: "/dashboard/client/bonus", icon: Gift, description: "Consulter les bonus" },
    ],
  },
  {
    key: "assistants",
    title: "Assistants",
    description: "Tous les assistants et supports du menu.",
    icon: MessageSquare,
    className: "border-cyan-200 bg-cyan-50 hover:bg-cyan-100/60",
    actions: [
      { label: "Guide assistants", to: "/dashboard/client/assistants-guide", icon: BookOpen, description: "Comprendre les assistants" },
      { label: "Assistant transfert", to: "/dashboard/client/agent-chat", icon: MessageSquare, description: "Aide aux transferts" },
      { label: "Support transfert", to: "/dashboard/client/transfer-support-agent", icon: MessageSquare, description: "Suivre une demande" },
      { label: "Assistant cash", to: "/dashboard/client/cash-agent", icon: MessageSquare, description: "Depot, retrait et capacite" },
      { label: "Assistant credit", to: "/dashboard/client/credit-agent", icon: MessageSquare, description: "Verifier une capacite" },
      { label: "Assistant KYC", to: "/dashboard/client/kyc-agent", icon: MessageSquare, description: "Statut, limites et documents" },
      { label: "Assistant wallet", to: "/dashboard/client/wallet-agent", icon: MessageSquare, description: "Solde et mouvements" },
      { label: "Support wallet", to: "/dashboard/client/wallet-support-agent", icon: MessageSquare, description: "Diagnostiquer un blocage" },
      { label: "Assistant escrow", to: "/dashboard/client/escrow-agent", icon: MessageSquare, description: "Suivi escrow" },
      { label: "Assistant P2P", to: "/dashboard/client/p2p-agent", icon: MessageSquare, description: "Suivi offres et trades" },
    ],
  },
  {
    key: "escrowP2p",
    title: "Escrow et P2P",
    description: "Paiement crypto et marche P2P.",
    icon: Shield,
    className: "border-violet-200 bg-violet-50 hover:bg-violet-100/60",
    actions: [
      { label: "Paiement crypto securise", to: "/dashboard/client/crypto-pay", icon: Shield, description: "Escrow crypto" },
      { label: "P2P Exchange", to: "/app/p2p", icon: Store, description: "Acheter ou vendre" },
      { label: "Mes Trades", to: "/app/p2p/my-trades", icon: Store, description: "Transactions en cours" },
      { label: "Mes Offres", to: "/app/p2p/my-offers", icon: Store, description: "Offres publiees" },
    ],
  },
  {
    key: "credit",
    title: "Credit et microfinance",
    description: "Credits, historique et situation financiere.",
    icon: CreditCard,
    className: "border-amber-200 bg-amber-50 hover:bg-amber-100/60",
    actions: [
      { label: "Historique credit", to: "/dashboard/client/credit-history", icon: CreditCard, description: "Historique complet" },
      { label: "Ligne de credit", to: "/dashboard/client/credit-line", icon: CreditCard, description: "Capacite disponible" },
      { label: "Microfinance", to: "/dashboard/client/microfinance", icon: Shield, description: "Services microfinance" },
      { label: "Credits", to: "/dashboard/client/loans", icon: CreditCard, description: "Demandes et suivi" },
      { label: "Situation financiere", to: "/dashboard/client/financial", icon: LineChart, description: "Vue financiere globale" },
    ],
  },
  {
    key: "community",
    title: "Communaute",
    description: "Fonctionnalites communautaires.",
    icon: RefreshCcw,
    className: "border-fuchsia-200 bg-fuchsia-50 hover:bg-fuchsia-100/60",
    actions: [{ label: "Tontines", to: "/dashboard/client/tontines", icon: RefreshCcw, description: "Cotisations et groupes" }],
  },
  {
    key: "account",
    title: "Compte",
    description: "Profil et informations personnelles.",
    icon: User,
    className: "border-sky-200 bg-sky-50 hover:bg-sky-100/60",
    actions: [{ label: "Profil", to: "/dashboard/client/profile", icon: User, description: "Parametres du compte" }],
  },
];
